import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Enable static generation for all pages by default
  output: "standalone",
  // Optimize images
  images: {
    formats: ["image/avif", "image/webp"],
  },
  // Enable static exports for marketing site
  // Pages are statically generated by default in App Router
};

export default nextConfig;
